export const ADD_PARTNER_IMG = "ADD_PARTNER_IMG"; 
export const IMG_PARTNER_DELATE = "IMG_PARTNER_DELATE";
export const IMG_PARTNER_HAS_ERROR = "IMG_PARTNER_HAS_ERROR";
export const ADD_PARTNER_IMG_LOADING = "ADD_PARTNER_IMG_LOADING";